name: Check Rust Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 3'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Check Rust Version
        run: make check

  create_issue:
    needs: check
    if: always() && (needs.check.result == 'failure')
    runs-on: ubuntu-latest

    steps:
      - name: Create Rust Update Issue
        run: gh issue create --title "Time to update to Rust" --body "Build update for next version of Rust" --label "enhancement" -R $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
