name: Build Stable Rust

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 3'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build and Test Stable
        run: |
          make build-arm64
          # make test
        env:
          RUST_VERSION: stable

  publish:
    needs: [test]
    if: github.repository == 'rust-serverless/lambda-rust'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Image
        shell: bash
        run: |
          make publish-tag-arm64
        env:
          RUST_VERSION: stable

  create_issue:
    needs: [publish]
    if: always() && (needs.publish.result == 'failure')
    runs-on: ubuntu-latest

    steps:
      - name: Create Error Issue
        run: gh issue create --title "Stable publication failed" --body "Stable publication failed" --label "bug" -R $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
